services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "gowallet"
    ports:
      - "5432:5432"

